# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('pin_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('like_count', models.IntegerField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Pinner',
            fields=[
                ('pinner_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('avatar', models.URLField(blank=True)),
                ('full_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.Pin'),
        ),
        migrations.AddField(
            model_name='board',
            name='pinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.Pinner'),
        ),
    ]
