# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
