# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import pinterest.models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinner',
            name='pinner_id',
            field=models.CharField(default=pinterest.models.create_id, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
