# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import pinterest.models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_auto_20171102_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_id',
            field=models.CharField(default=pinterest.models.create_id, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_id',
            field=models.CharField(default=pinterest.models.create_id, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
